### ISSUE TITLE
Don't save API key in config

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/cloudflare#2]
* Save this in the state system instead (so that it is in the db not not in the codebase) See [state_get()](https://docs.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/state_get/1) and [state_set()](https://docs.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/state_set/1), use [state_del()](https://docs.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/state_del/1) in `hook_uninstall()`.

* Allow the value to be overridden via `settings.php` by using [settings_get()](https://docs.backdropcms.org/api/backdrop/core%21includes%21bootstrap.inc/function/settings_get/1)

**Comment by larsdesigns** [comment]
1. Created pull request: https://github.com/backdrop-contrib/cloudflare/pull/3
